apiVersion: apps/v1
kind: Deployment
metadata:
  name: demo-backend
  namespace: demo-apps
spec:
  replicas: 1
  selector:
    matchLabels:
      app: demo-backend
  template:
    metadata:
      labels:
        app: demo-backend
    spec:
      containers:
        - name: demo-backend
          image: ghcr.io/recmanj/demo-backend:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8000
          env:
            - name: DATABASE_URL
              value: "postgresql://demo:demo@postgres.demo-apps.svc.cluster.local:5432/demo"
